# Generated by Django 4.2 on 2023-05-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
